name: "dbt_takehome"
version: "1.0.0"
config-version: 2

profile: "dbt-takehome"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["models/tests"]

models:
  dbt_takehome:
    +materialized: view
    staging:
      +schema: staging
    marts:
      +schema: marts